#!/bin/sh

ALARM="/tmp/poweralarm"
CURRENT_LEVEL="$(herodot battery get level)"
LEVEL=80
TIMEOUT=60

alarm() {
    while true; do
        if [ "$CURRENT_LEVEL" -lt "$LEVEL" ]; then
            if [ ! -f "$ALARM" ]; then
                zenity --warning --text="Connect the charger to avoid shutdown" --title="Power Alarm"
                touch "$ALARM"
            fi
        else
            if [ -f "$ALARM" ]; then
                rm "$ALARM"
            fi
        fi
        sleep "$TIMEOUT"
    done
}

toggle() {
    if [ -f "$ALARM" ]; then
        rm "$ALARM"
    fi

    herodot performance set mode "$1"
    herodot idle set state "$2"
}

moder() {
    udevadm monitor --udev --property | while IFS= read -r line; do
        case "$line" in
            POWER_SUPPLY_ONLINE=*)
                state="${line#*=}"
                [ "$state" = "1" ] && toggle "performance" "off" || toggle "power" "on"
                ;;
        esac
    done
}

alarm &
moder



